name: flutter_news
description: All new trending news application made with flutter

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image:
  get:
  dio:
  flutter_paginator:
  google_fonts:
  webview_flutter:
  font_awesome_flutter:
  shimmer:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/